INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Adler', 'https://en.wikipedia.org/wiki/Adler_(automobile)', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('AIST', 'https://en.wikipedia.org/wiki/Aist_Bicycles', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Aprilia', 'https://en.wikipedia.org/wiki/Aprilia', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Ariel', 'https://en.wikipedia.org/wiki/Ariel_(vehicle)', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Baltik vairas', 'https://en.wikipedia.org/wiki/Baltik_vairas', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Barnes Cycle Company', 'https://en.wikipedia.org/wiki/History_of_cycling_in_Syracuse,_New_York#Barnes_Cycle_Company', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Battaglin', 'https://en.wikipedia.org/wiki/Giovanni_Battaglin#Retirement', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Berlin &amp; Racycle Manufacturing Company', 'https://en.wikipedia.org/wiki/The_Arthur_Pequegnat_Clock_Company', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Bontrager', 'https://en.wikipedia.org/wiki/Keith_Bontrager#Bicycles', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Bootie', 'https://en.wikipedia.org/wiki/Bootie_(bicycle)', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Bradbury', 'https://en.wikipedia.org/wiki/Bradbury_Motor_Cycles', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('BSA', 'https://en.wikipedia.org/wiki/Birmingham_Small_Arms_Company', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('B’Twin', 'https://en.wikipedia.org/wiki/Decathlon_Group', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Clément', 'https://en.wikipedia.org/wiki/Adolphe_Cl%C3%A9ment#C.C3.A9ment_cycles', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Coventry-Eagle', 'https://en.wikipedia.org/wiki/Coventry-Eagle', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Cycleuropa Group', 'https://en.wikipedia.org/wiki/Cycleuropa_Group', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Defiance Cycle Company', 'https://en.wikipedia.org/wiki/Defiance_Cycle_Company', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Demorest', 'https://en.wikipedia.org/wiki/Lycoming_Engines#Sewing_machines.2C_bicycles_and_fashion', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Dunelt', 'https://en.wikipedia.org/wiki/Dunelt_Motorcycles', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Ērenpreiss Bicycles', 'https://en.wikipedia.org/wiki/%C4%92renpreiss_Bicycles', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Excelsior', 'https://en.wikipedia.org/wiki/Excelsior_Motor_Company', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Gimson', 'https://en.wikipedia.org/wiki/Gimson_(cycles)', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Gräf &amp; Stift', 'https://en.wikipedia.org/wiki/Gr%C3%A4f_%26_Stift', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Gustavs Ērenpreis Bicycle Factory', 'https://en.wikipedia.org/wiki/Gustavs_%C4%92renpreis_Bicycle_Factory', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Harley-Davidson', 'https://en.wikipedia.org/wiki/Harley-Davidson#Bicycles', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Henley Bicycle Works', 'https://en.wikipedia.org/wiki/Micajah_C._Henley', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Hoffmann', 'https://en.wikipedia.org/wiki/Hoffmann_(motorcycle)', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Husqvarna', 'https://en.wikipedia.org/wiki/Husqvarna_Motorcycles#Bicycle_manufacturing', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Indian', 'https://en.wikipedia.org/wiki/Indian_(motorcycle)#Bicycles', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('IFA', 'https://en.wikipedia.org/wiki/Industrieverband_Fahrzeugbau', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Ivel Cycle Works', 'https://en.wikipedia.org/wiki/Dan_Albone', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Kangaroo', 'https://en.wikipedia.org/wiki/Kangaroo_bicycle', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Karbon Kinetics Limited', 'https://en.wikipedia.org/wiki/Karbon_Kinetics_Limited', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Kia', 'https://en.wikipedia.org/wiki/Kia_Motors', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Merckx', 'https://en.wikipedia.org/wiki/Eddy_Merckx', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Minerva', 'https://en.wikipedia.org/wiki/Minerva_(automobile)#Bicycles_and_motorcycles', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Mochet', 'https://en.wikipedia.org/wiki/Mochet', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Motobécane', 'https://en.wikipedia.org/wiki/Motob%C3%A9cane', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Nagasawa', 'https://en.wikipedia.org/wiki/Yoshiaki_Nagasawa', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('NEXT', 'https://en.wikipedia.org/wiki/NEXT_(bicycle_company)', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('NSU', 'https://en.wikipedia.org/wiki/NSU_Motorenwerke#NSU_bicycles', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Olive Wheel Company', 'https://en.wikipedia.org/wiki/History_of_cycling_in_Syracuse,_New_York#Olive_Wheel_Company', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Órbita', 'https://en.wikipedia.org/wiki/%C3%93rbita_bicycles', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Overman Wheel Company', 'https://en.wikipedia.org/wiki/Overman_Wheel_Company', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Premier', 'https://en.wikipedia.org/wiki/Premier_Motorcycles', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Quality Bicycle Products', 'https://en.wikipedia.org/wiki/Quality_Bicycle_Products', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('R+E Cycles', 'https://en.wikipedia.org/wiki/R%2BE_Cycles', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Rabasa Cycles', 'https://en.wikipedia.org/wiki/Rabasa_Cycles', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Rhoades Car', 'https://en.wikipedia.org/wiki/Rhoades_Car', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Riley Cycle Company', 'https://en.wikipedia.org/wiki/Riley_(motor-car)#Riley_Cycle_Company', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('ROSE Bikes', 'https://en.wikipedia.org/wiki/ROSE_Bikes', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Salcano (bicycle)', 'https://en.wikipedia.org/wiki/Salcano_(bicycle)', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Maskinfabriks-aktiebolaget Scania', 'https://en.wikipedia.org/wiki/Maskinfabriks-aktiebolaget_Scania', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Simpel', 'https://en.wikipedia.org/wiki/Simpel', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Singer', 'https://en.wikipedia.org/wiki/Singer_(car)#Bicycles', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Softride', 'https://en.wikipedia.org/wiki/Softride', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Solifer', 'https://en.wikipedia.org/wiki/Solifer', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('SOMA Fabrications', 'https://en.wikipedia.org/wiki/SOMA_Fabrications', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Star Cycle Company', 'https://en.wikipedia.org/wiki/Star_Motor_Company#Bicycles', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Stearns', 'https://en.wikipedia.org/wiki/E._C._Stearns_Bicycle_Agency', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Steyr', 'https://en.wikipedia.org/wiki/Steyr-Daimler-Puch', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Sunbeam', 'https://en.wikipedia.org/wiki/Sunbeam_Cycles#Sunbeam_bicycles', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Swift Folder', 'https://en.wikipedia.org/wiki/Swift_Folder', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Syracuse Cycle Company', 'https://en.wikipedia.org/wiki/History_of_cycling_in_Syracuse,_New_York#Syracuse_Cycle_Company', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Thomas', 'https://en.wikipedia.org/wiki/Thomas_Motor_Company', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Tube Investments', 'https://en.wikipedia.org/wiki/Tube_Investments', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Velocite Bikes', 'https://en.wikipedia.org/wiki/Velocite_Bikes', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Victoria', 'https://en.wikipedia.org/wiki/Victoria_(motorcycle)', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Wanderer', 'https://en.wikipedia.org/wiki/Wanderer_(car)', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Westfield Maufacturing', 'https://en.wikipedia.org/wiki/History_of_cycling_in_Syracuse,_New_York#Westfield_Manufacturing', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Whippet', 'https://en.wikipedia.org/wiki/Whippet_(bicycle)', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Wittson Custom Ti Cycles', 'https://en.wikipedia.org/wiki/Wittson_Custom_Ti_Cycles', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Worden Bicycles', 'https://en.wikipedia.org/wiki/History_of_cycling_in_Syracuse,_New_York#Worden_Bicycles', true);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Whyte', 'https://en.wikipedia.org/wiki/Whyte_(bicycles)', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Zündapp', 'https://en.wikipedia.org/wiki/Z%C3%BCndapp', false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Alps', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Amanda (Tokyo)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Amuna (written "AMVNA", manufactured by Matsumoto Cycle, Sendai)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('A.N. Design Works (Core Japan, Tokyo)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Araya', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('ARES', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Asuka (Nara)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Baramon (Kurume)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Cateye', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Cherubim (Machida, Tokyo)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Crafted (Fukui)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Deki', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Elan', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Emme Akko (Miyako)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('<a href="#cite_note-1">[1]</a>', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Fury', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Ganwell (Kyoto)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Hirose (Kodaira, Tokyo)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Holks', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Honjo (Tottori)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Ikesho', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Iribe (Nara)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Kalavinka (made by Tsukumo, Tokyo)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Kusano Engineering (Tokyo)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Mikado', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Kiyo Miyazawa (Tokyo)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Miyuki (Tokyo)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('http://www.mizutanibike.co.jp/', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Nagasawa', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Nakagawa (Osaka)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Nakamichi', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Ono', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Polaris', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Project M (Tsukuba, Ibaraki)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Raizin (Kiryu, Gunma)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Ravanello (made by Takamura, Tokyo)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Reminton', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Sannow', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Shimazaki (Tokyo)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Silk', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Smith', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Suntour', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Tano', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Toei (Kawaguchi, Saitama)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Tokyobike', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Tsunoda (Nagoya, Japan — also manufactured Lotus brand)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Tubagra', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Vigore (Kyoto)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Vlaams', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Vogue (made by Orient, Kamakura)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Zebrakenko', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Zunow (Osaka)', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('List of bicycle brands and manufacturing companies', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('<b><a href="#cite_ref-1"><span class="cite-accessibility-label">Jump up </span>^</a></b>', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('1984 Centurion Catalog, U.S.', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('<abbr title="View this template" style=";;background:none transparent;border:none;">v</abbr>', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('<abbr title="Discuss this template" style=";;background:none transparent;border:none;">t</abbr>', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('<abbr title="Edit this template" style=";;background:none transparent;border:none;">e</abbr>', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('Nagasawa', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('SunTour', null, false);
INSERT INTO manufacturer (name, wikipedia_url, discontinued) VALUES ('SunTour', null, false);
